---
language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks
before_install: "gem update bundler"
script: "bundle exec rake ci"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - ruby-head
  - jruby-9000
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9000
  fast_finish: true
branches:
  only: master
notifications:
  email: false
